// <auto-generated />
using System;
using CMCS_Web_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMCS_Web_App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CMCS_Web_App.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateApproved")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoursWorked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("LecturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupportingDocumentPath")
                        .HasColumnType("TEXT");

                    b.HasKey("ClaimId");

                    b.HasIndex("LecturerId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("CMCS_Web_App.Models.Coordinator", b =>
                {
                    b.Property<int>("CoordinatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CoordinatorId");

                    b.ToTable("Coordinators");
                });

            modelBuilder.Entity("CMCS_Web_App.Models.HR", b =>
                {
                    b.Property<int>("HRId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HRId");

                    b.ToTable("HR");
                });

            modelBuilder.Entity("CMCS_Web_App.Models.Lecturer", b =>
                {
                    b.Property<int>("LecturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HRId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RatePerHour")
                        .HasColumnType("TEXT");

                    b.HasKey("LecturerId");

                    b.HasIndex("HRId");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("CMCS_Web_App.Models.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ManagerId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("CMCS_Web_App.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "Lofentse13@CMCSLEC.com",
                            FirstName = "Lofentse",
                            LastName = "Moagi",
                            PasswordHash = "BD5CE2FCF52FD92709E65388151D63CEFC65B75F0BBC7DCC8D401764BDFAE427",
                            Role = "Lecturer"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "Karabo28@CMCSLEC.com",
                            FirstName = "Karabo",
                            LastName = "Kgoebane",
                            PasswordHash = "B7E307660E1611CB42BCB28E4BB4A6465CCB5EC2E028CA4BE8B84E8787929A38",
                            Role = "Lecturer"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "Claudia06@CMCSLEC.com",
                            FirstName = "Claudia",
                            LastName = "Brander",
                            PasswordHash = "2FB451F9569989E892CED96048464D6739285A0A5FE00A1A12C47E9D3AF93762",
                            Role = "Lecturer"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "Co-ordinator@CoordCMCS.com",
                            FirstName = "Steph",
                            LastName = "Curry",
                            PasswordHash = "FD7D77DE225B32549F1F537D378526AD307F575C5B6D66370A50C80CF54E081A",
                            Role = "Coordinator"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "Manager@ManCMCS.com",
                            FirstName = "Ethan",
                            LastName = "Hunt",
                            PasswordHash = "8C454536B6E2B8B29A1D839AA3C5CCF0AB57A590D619739B23A32D11585220C9",
                            Role = "Manager"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "HR@ResourcesCMCS.com",
                            FirstName = "Shrek",
                            LastName = "Fiona",
                            PasswordHash = "93759AF6F455B1610E615483CF5EA847B0B7248055C16BE328C9F292D8695A9C",
                            Role = "HR"
                        });
                });

            modelBuilder.Entity("CMCS_Web_App.Models.Claim", b =>
                {
                    b.HasOne("CMCS_Web_App.Models.Lecturer", "Lecturer")
                        .WithMany("Claims")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("CMCS_Web_App.Models.Lecturer", b =>
                {
                    b.HasOne("CMCS_Web_App.Models.HR", null)
                        .WithMany("ManagedLecturers")
                        .HasForeignKey("HRId");
                });

            modelBuilder.Entity("CMCS_Web_App.Models.HR", b =>
                {
                    b.Navigation("ManagedLecturers");
                });

            modelBuilder.Entity("CMCS_Web_App.Models.Lecturer", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
